'use strict';
// `devsharp setup <host>`: connects DevSharp to AI coding CLIs other than Claude Code
// (Claude Code uses the plugin system instead). Every change is explicit and
// reversible: settings files are backed up before editing, only DevSharp's own
// entries are added or removed, and anything else in the file is left untouched.
//
//   codex     ~/.codex/hooks.json             UserPromptSubmit + Stop (systemMessage)
//   gemini    ~/.gemini/settings.json         BeforeAgent + AfterTool + AfterAgent (systemMessage)
//   opencode  ~/.config/opencode/plugins/devsharp.js   toast pop-ups on prompt / tool / idle
//
// Anything else (Freebuff/Codebuff, Aider, Copilot CLI, Cursor, ...): `devsharp watch`.

const fs = require('fs');
const os = require('os');
const path = require('path');
const { PKG_ROOT } = require('../core/paths');

const HOOK = path.join(PKG_ROOT, 'src', 'claude', 'hook.js');
const MARK = 'devsharp';

function q(s) {
  // Quote a path for a shell command string (hosts run `command` through a shell).
  return process.platform === 'win32' ? `"${s}"` : `'${s.replace(/'/g, `'\\''`)}'`;
}

function hookCmd(event, host) {
  return `${q(process.execPath)} ${q(HOOK)} ${event} --host=${host}`;
}

function readJsonFile(file) {
  if (!fs.existsSync(file)) return {};
  const raw = fs.readFileSync(file, 'utf8');
  if (!raw.trim()) return {};
  const j = JSON.parse(raw); // refuse to touch a file we cannot parse
  if (!j || typeof j !== 'object' || Array.isArray(j)) throw new Error(`${file} is not a JSON object`);
  return j;
}

function backupAndWrite(file, data) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  if (fs.existsSync(file)) fs.copyFileSync(file, `${file}.devsharp-backup`);
  fs.writeFileSync(file, `${JSON.stringify(data, null, 2)}\n`);
}

const isOurs = (h) => h && typeof h.command === 'string' && h.command.includes(HOOK.split(path.sep).join(path.sep)) || (h && typeof h.name === 'string' && h.name.startsWith(MARK));

// Remove DevSharp entries from a Claude-style hooks object, dropping empty groups.
function stripHooks(hooks) {
  for (const ev of Object.keys(hooks)) {
    if (!Array.isArray(hooks[ev])) continue;
    hooks[ev] = hooks[ev]
      .map((g) => (g && Array.isArray(g.hooks) ? { ...g, hooks: g.hooks.filter((h) => !isOurs(h)) } : g))
      .filter((g) => !(g && Array.isArray(g.hooks) && g.hooks.length === 0));
    if (!hooks[ev].length) delete hooks[ev];
  }
  return hooks;
}

const HOSTS = {
  codex: {
    name: 'Codex CLI',
    file: (home) => path.join(home, '.codex', 'hooks.json'),
    // Codex shows systemMessage for UserPromptSubmit and Stop (not PostToolUse).
    events: { UserPromptSubmit: 'prompt', Stop: 'stop', SessionStart: 'session-start', SessionEnd: 'session-end' },
    entry: (ev) => ({ type: 'command', command: hookCmd(ev, 'codex'), timeout: ev === 'session-end' ? 2 : 10 }),
  },
  gemini: {
    name: 'Gemini CLI',
    file: (home) => path.join(home, '.gemini', 'settings.json'),
    events: { BeforeAgent: 'prompt', AfterTool: 'tool', AfterAgent: 'stop', SessionStart: 'session-start', SessionEnd: 'session-end' },
    entry: (ev) => ({ type: 'command', name: `${MARK}-${ev}`, command: hookCmd(ev, 'gemini'), timeout: 10000 }),
  },
};

function setupHooksHost(key, home) {
  const h = HOSTS[key];
  const file = h.file(home);
  const cfg = readJsonFile(file);
  cfg.hooks = stripHooks(cfg.hooks && typeof cfg.hooks === 'object' ? cfg.hooks : {});
  for (const [hostEvent, ev] of Object.entries(h.events)) {
    if (!Array.isArray(cfg.hooks[hostEvent])) cfg.hooks[hostEvent] = [];
    cfg.hooks[hostEvent].push({ hooks: [h.entry(ev)] });
  }
  backupAndWrite(file, cfg);
  return file;
}

function removeHooksHost(key, home) {
  const file = HOSTS[key].file(home);
  if (!fs.existsSync(file)) return null;
  const cfg = readJsonFile(file);
  if (!cfg.hooks) return null;
  cfg.hooks = stripHooks(cfg.hooks);
  if (!Object.keys(cfg.hooks).length) delete cfg.hooks;
  backupAndWrite(file, cfg);
  return file;
}

// opencode loads JS plugins from ~/.config/opencode/plugins/. The plugin calls the
// same hook and shows the card as a TUI toast (a real pop-up that fades away).
function opencodePlugin() {
  return `// DevSharp for opencode (generated by \`devsharp setup opencode\`; remove with \`devsharp setup opencode --remove\`).
// Shows learning cards as toasts while the agent works. Calls no model.
import { spawnSync } from "node:child_process";

const NODE = ${JSON.stringify(process.execPath)};
const HOOK = ${JSON.stringify(HOOK)};

function card(event, input) {
  try {
    const r = spawnSync(NODE, [HOOK, event, "--host=opencode"], { input: JSON.stringify(input), encoding: "utf8", timeout: 10000 });
    const msg = r.stdout ? JSON.parse(r.stdout).systemMessage : "";
    if (!msg) return null;
    const lines = msg.trim().split("\\n").map((l) => l.replace(/^(╭─ |╰─ |│  |│)/, ""));
    return { title: lines[0], message: lines.slice(1).join("\\n").replace(/\\n{3,}/g, "\\n\\n").trim() };
  } catch {
    return null;
  }
}

export const DevSharp = async ({ client, directory }) => {
  const show = async (event, input) => {
    const c = card(event, { cwd: directory, ...input });
    if (c) await client.tui.showToast({ body: { title: c.title, message: c.message, variant: "info", duration: 45000 } }).catch(() => {});
  };
  return {
    "chat.message": async (input) => show("prompt", { session_id: input.sessionID, prompt: "(prompt)" }),
    "tool.execute.after": async (input) => show("tool", { session_id: input.sessionID }),
    event: async ({ event }) => {
      if (event.type === "session.idle") await show("stop", { session_id: event.properties && event.properties.sessionID });
    },
  };
};
`;
}

function opencodeFile(home) {
  const base = process.env.XDG_CONFIG_HOME ? path.resolve(process.env.XDG_CONFIG_HOME) : path.join(home, '.config');
  return path.join(base, 'opencode', 'plugins', 'devsharp.js');
}

function setup(host, { remove = false, home = os.homedir() } = {}) {
  if (host === 'opencode') {
    const file = opencodeFile(home);
    if (remove) {
      if (fs.existsSync(file)) fs.unlinkSync(file);
      return { host: 'opencode', file, removed: true };
    }
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, opencodePlugin());
    return { host: 'opencode', file };
  }
  if (!HOSTS[host]) throw new Error(`Unknown host "${host}". Use: codex, gemini, opencode (Claude Code: install the plugin; anything else: devsharp watch)`);
  const file = remove ? removeHooksHost(host, home) : setupHooksHost(host, home);
  return { host, file, removed: remove };
}

module.exports = { setup, stripHooks, opencodePlugin, HOSTS, HOOK };
