'use strict';
// Static signal -> canonical topic id tables used by detect.js.
// Every entry is a list of [topicId, weight] pairs, weight in 0..1. The
// detector multiplies this by the strength of the signal kind (explicit
// dependency 1.0, compose image 0.9, config file 0.8, extension census <= 0.7).
// Topic ids MUST be the canonical ids from docs/CONTRACT.md.

const TOPICS = [
  'javascript', 'typescript', 'python', 'go', 'rust', 'java', 'bash',
  'react', 'nextjs', 'css', 'browser',
  'nodejs', 'http', 'auth', 'api-design',
  'sql', 'postgresql', 'mysql', 'redis', 'mongodb', 'sqlite', 'prisma',
  'docker', 'kubernetes', 'git', 'linux', 'ci-cd',
  'aws',
  'web-security', 'tls', 'cryptography',
  'tcp', 'dns',
  'distributed-systems',
  'system-design', 'caching',
  'ai-ml', 'llm',
  'algorithms', 'data-structures', 'memory', 'concurrency',
];

// ---- npm (package.json dependencies) -------------------------------------
const NPM = {
  react: [['react', 1], ['browser', 0.4]],
  'react-dom': [['react', 1], ['browser', 0.5]],
  'react-native': [['react', 0.8]],
  preact: [['react', 0.6], ['browser', 0.4]],
  next: [['nextjs', 1], ['react', 0.9], ['http', 0.4]],
  vue: [['browser', 0.6]],
  svelte: [['browser', 0.6]],
  '@angular/core': [['browser', 0.6], ['typescript', 0.6]],
  vite: [['browser', 0.4]],
  webpack: [['browser', 0.3]],
  tailwindcss: [['css', 0.9]],
  sass: [['css', 0.8]],
  'node-sass': [['css', 0.8]],
  postcss: [['css', 0.6]],
  'styled-components': [['css', 0.7], ['react', 0.4]],
  '@emotion/react': [['css', 0.7], ['react', 0.4]],
  express: [['http', 1], ['nodejs', 0.9], ['api-design', 0.6]],
  fastify: [['http', 1], ['nodejs', 0.9], ['api-design', 0.6]],
  koa: [['http', 1], ['nodejs', 0.9]],
  hono: [['http', 1], ['api-design', 0.5]],
  '@nestjs/core': [['http', 1], ['nodejs', 0.9], ['api-design', 0.8], ['typescript', 0.7]],
  '@hapi/hapi': [['http', 1], ['nodejs', 0.9]],
  'graphql': [['api-design', 0.9]],
  '@apollo/server': [['api-design', 0.9], ['http', 0.6]],
  '@trpc/server': [['api-design', 0.8]],
  axios: [['http', 0.5]],
  'socket.io': [['http', 0.6], ['tcp', 0.4]],
  ws: [['http', 0.5], ['tcp', 0.4]],
  prisma: [['prisma', 1], ['sql', 0.7]],
  '@prisma/client': [['prisma', 1], ['sql', 0.7]],
  'drizzle-orm': [['sql', 0.9]],
  typeorm: [['sql', 0.9]],
  sequelize: [['sql', 0.9]],
  knex: [['sql', 0.9]],
  pg: [['postgresql', 1], ['sql', 0.8]],
  postgres: [['postgresql', 1], ['sql', 0.8]],
  mysql: [['mysql', 1], ['sql', 0.8]],
  mysql2: [['mysql', 1], ['sql', 0.8]],
  'better-sqlite3': [['sqlite', 1], ['sql', 0.8]],
  sqlite3: [['sqlite', 1], ['sql', 0.8]],
  mongoose: [['mongodb', 1]],
  mongodb: [['mongodb', 1]],
  redis: [['redis', 1], ['caching', 0.6]],
  ioredis: [['redis', 1], ['caching', 0.6]],
  bullmq: [['redis', 0.8], ['distributed-systems', 0.6]],
  bull: [['redis', 0.8], ['distributed-systems', 0.6]],
  'lru-cache': [['caching', 0.8]],
  kafkajs: [['distributed-systems', 1]],
  amqplib: [['distributed-systems', 1]],
  typescript: [['typescript', 1]],
  'ts-node': [['typescript', 0.9], ['nodejs', 0.6]],
  tsx: [['typescript', 0.8], ['nodejs', 0.6]],
  '@types/node': [['nodejs', 0.8], ['typescript', 0.6]],
  jsonwebtoken: [['auth', 1], ['cryptography', 0.5], ['web-security', 0.5]],
  jose: [['auth', 1], ['cryptography', 0.6]],
  passport: [['auth', 1]],
  'next-auth': [['auth', 1], ['nextjs', 0.6]],
  '@auth/core': [['auth', 1]],
  bcrypt: [['cryptography', 0.8], ['auth', 0.7]],
  bcryptjs: [['cryptography', 0.8], ['auth', 0.7]],
  argon2: [['cryptography', 0.8], ['auth', 0.7]],
  helmet: [['web-security', 1], ['http', 0.5]],
  cors: [['web-security', 0.7], ['http', 0.6]],
  'csurf': [['web-security', 0.9]],
  'aws-sdk': [['aws', 1]],
  '@tensorflow/tfjs': [['ai-ml', 1]],
  '@tensorflow/tfjs-node': [['ai-ml', 1]],
  'onnxruntime-node': [['ai-ml', 1]],
  openai: [['llm', 1]],
  '@anthropic-ai/sdk': [['llm', 1]],
  langchain: [['llm', 1]],
  ai: [['llm', 0.8]],
  'llama.rn': [['llm', 1]],
  'node-llama-cpp': [['llm', 1]],
  '@kubernetes/client-node': [['kubernetes', 1]],
  dockerode: [['docker', 1]],
  puppeteer: [['browser', 0.8]],
  playwright: [['browser', 0.8]],
  '@playwright/test': [['browser', 0.7]],
};

// Scoped/prefix rules, checked when no exact match exists.
const NPM_PREFIX = [
  ['@aws-sdk/', [['aws', 1]]],
  ['@tensorflow/', [['ai-ml', 1]]],
  ['@langchain/', [['llm', 1]]],
  ['@nestjs/', [['nodejs', 0.8], ['typescript', 0.6]]],
  ['@prisma/', [['prisma', 0.9]]],
  ['@next/', [['nextjs', 0.8]]],
  ['@radix-ui/', [['react', 0.6]]],
  ['@tanstack/react-', [['react', 0.7]]],
  ['@apollo/', [['api-design', 0.8]]],
  ['@types/react', [['react', 0.6]]],
];

// ---- Python ---------------------------------------------------------------
const PY = {
  django: [['http', 1], ['api-design', 0.6], ['sql', 0.6], ['python', 0.8]],
  djangorestframework: [['api-design', 1], ['http', 0.8]],
  flask: [['http', 1], ['api-design', 0.6], ['python', 0.8]],
  fastapi: [['http', 1], ['api-design', 1], ['python', 0.8]],
  starlette: [['http', 0.9]],
  uvicorn: [['http', 0.7], ['concurrency', 0.4]],
  gunicorn: [['http', 0.7]],
  aiohttp: [['http', 0.9], ['concurrency', 0.6]],
  requests: [['http', 0.5]],
  httpx: [['http', 0.6]],
  pydantic: [['api-design', 0.5]],
  sqlalchemy: [['sql', 1]],
  alembic: [['sql', 0.8]],
  psycopg: [['postgresql', 1], ['sql', 0.8]],
  psycopg2: [['postgresql', 1], ['sql', 0.8]],
  'psycopg2-binary': [['postgresql', 1], ['sql', 0.8]],
  asyncpg: [['postgresql', 1], ['sql', 0.8], ['concurrency', 0.4]],
  pymysql: [['mysql', 1], ['sql', 0.8]],
  mysqlclient: [['mysql', 1], ['sql', 0.8]],
  redis: [['redis', 1], ['caching', 0.6]],
  pymongo: [['mongodb', 1]],
  motor: [['mongodb', 1], ['concurrency', 0.4]],
  celery: [['distributed-systems', 0.9], ['concurrency', 0.5]],
  'kafka-python': [['distributed-systems', 1]],
  'confluent-kafka': [['distributed-systems', 1]],
  pika: [['distributed-systems', 1]],
  torch: [['ai-ml', 1]],
  tensorflow: [['ai-ml', 1]],
  keras: [['ai-ml', 1]],
  'scikit-learn': [['ai-ml', 1]],
  sklearn: [['ai-ml', 1]],
  numpy: [['ai-ml', 0.6]],
  pandas: [['ai-ml', 0.7]],
  scipy: [['ai-ml', 0.6]],
  xgboost: [['ai-ml', 1]],
  transformers: [['llm', 1], ['ai-ml', 0.8]],
  'sentence-transformers': [['llm', 0.9], ['ai-ml', 0.8]],
  openai: [['llm', 1]],
  anthropic: [['llm', 1]],
  langchain: [['llm', 1]],
  'llama-index': [['llm', 1]],
  'llama-cpp-python': [['llm', 1]],
  boto3: [['aws', 1]],
  botocore: [['aws', 0.9]],
  cryptography: [['cryptography', 1]],
  pyjwt: [['auth', 1], ['cryptography', 0.5]],
  'python-jose': [['auth', 1], ['cryptography', 0.5]],
  passlib: [['auth', 0.8], ['cryptography', 0.6]],
  bcrypt: [['auth', 0.7], ['cryptography', 0.8]],
  kubernetes: [['kubernetes', 1]],
  docker: [['docker', 1]],
};

// ---- Go (module path substrings) -----------------------------------------
const GO = [
  ['github.com/gin-gonic/gin', [['http', 1], ['api-design', 0.6]]],
  ['github.com/labstack/echo', [['http', 1], ['api-design', 0.6]]],
  ['github.com/gofiber/fiber', [['http', 1], ['api-design', 0.6]]],
  ['github.com/go-chi/chi', [['http', 1]]],
  ['github.com/gorilla/mux', [['http', 1]]],
  ['github.com/jackc/pgx', [['postgresql', 1], ['sql', 0.8]]],
  ['github.com/lib/pq', [['postgresql', 1], ['sql', 0.8]]],
  ['github.com/go-sql-driver/mysql', [['mysql', 1], ['sql', 0.8]]],
  ['github.com/mattn/go-sqlite3', [['sqlite', 1], ['sql', 0.8]]],
  ['modernc.org/sqlite', [['sqlite', 1], ['sql', 0.8]]],
  ['gorm.io/gorm', [['sql', 1]]],
  ['github.com/jmoiron/sqlx', [['sql', 1]]],
  ['github.com/redis/go-redis', [['redis', 1], ['caching', 0.6]]],
  ['github.com/go-redis/redis', [['redis', 1], ['caching', 0.6]]],
  ['go.mongodb.org/mongo-driver', [['mongodb', 1]]],
  ['google.golang.org/grpc', [['api-design', 0.9], ['distributed-systems', 0.7], ['http', 0.5]]],
  ['google.golang.org/protobuf', [['api-design', 0.6]]],
  ['github.com/segmentio/kafka-go', [['distributed-systems', 1]]],
  ['github.com/IBM/sarama', [['distributed-systems', 1]]],
  ['github.com/Shopify/sarama', [['distributed-systems', 1]]],
  ['github.com/nats-io/', [['distributed-systems', 1]]],
  ['github.com/rabbitmq/amqp091-go', [['distributed-systems', 1]]],
  ['github.com/aws/aws-sdk-go', [['aws', 1]]],
  ['k8s.io/client-go', [['kubernetes', 1]]],
  ['k8s.io/api', [['kubernetes', 0.9]]],
  ['sigs.k8s.io/controller-runtime', [['kubernetes', 1]]],
  ['github.com/docker/docker', [['docker', 1]]],
  ['github.com/golang-jwt/jwt', [['auth', 1], ['cryptography', 0.5]]],
  ['golang.org/x/crypto', [['cryptography', 0.9]]],
  ['golang.org/x/sync', [['concurrency', 0.8]]],
  ['github.com/sashabaranov/go-openai', [['llm', 1]]],
  ['github.com/anthropics/anthropic-sdk-go', [['llm', 1]]],
];

// ---- Rust crates ([dependencies] keys) -----------------------------------
const CARGO = {
  tokio: [['concurrency', 1]],
  'async-std': [['concurrency', 1]],
  rayon: [['concurrency', 1]],
  crossbeam: [['concurrency', 0.9]],
  futures: [['concurrency', 0.7]],
  axum: [['http', 1], ['api-design', 0.6]],
  'actix-web': [['http', 1], ['api-design', 0.6]],
  rocket: [['http', 1]],
  warp: [['http', 1]],
  hyper: [['http', 1], ['tcp', 0.4]],
  reqwest: [['http', 0.6]],
  tonic: [['api-design', 0.9], ['distributed-systems', 0.6]],
  sqlx: [['sql', 1]],
  diesel: [['sql', 1]],
  'sea-orm': [['sql', 1]],
  'tokio-postgres': [['postgresql', 1], ['sql', 0.8]],
  postgres: [['postgresql', 1], ['sql', 0.8]],
  rusqlite: [['sqlite', 1], ['sql', 0.8]],
  mysql: [['mysql', 1], ['sql', 0.8]],
  redis: [['redis', 1], ['caching', 0.6]],
  mongodb: [['mongodb', 1]],
  serde: [['api-design', 0.3]],
  serde_json: [['api-design', 0.3]],
  rustls: [['tls', 1]],
  'tokio-rustls': [['tls', 1]],
  openssl: [['tls', 0.9], ['cryptography', 0.7]],
  ring: [['cryptography', 1]],
  sha2: [['cryptography', 0.8]],
  jsonwebtoken: [['auth', 1], ['cryptography', 0.5]],
  'aws-sdk-s3': [['aws', 1]],
  'aws-config': [['aws', 1]],
  rdkafka: [['distributed-systems', 1]],
  lapin: [['distributed-systems', 1]],
  kube: [['kubernetes', 1]],
  candle: [['ai-ml', 1]],
  'candle-core': [['ai-ml', 1]],
  tch: [['ai-ml', 1]],
  'async-openai': [['llm', 1]],
  trust_dns_resolver: [['dns', 1]],
  'hickory-resolver': [['dns', 1]],
};
const CARGO_PREFIX = [['aws-sdk-', [['aws', 1]]]];

// ---- Java / Kotlin (artifactId substrings in pom.xml / build.gradle) -----
const JVM = [
  ['spring-boot', [['http', 0.9], ['api-design', 0.7], ['java', 0.8]]],
  ['spring-webmvc', [['http', 1]]],
  ['spring-webflux', [['http', 1], ['concurrency', 0.6]]],
  ['spring-security', [['auth', 1], ['web-security', 0.8]]],
  ['spring-data-jpa', [['sql', 1]]],
  ['hibernate', [['sql', 1]]],
  ['mybatis', [['sql', 1]]],
  ['jooq', [['sql', 1]]],
  ['postgresql', [['postgresql', 1], ['sql', 0.8]]],
  ['mysql-connector', [['mysql', 1], ['sql', 0.8]]],
  ['sqlite-jdbc', [['sqlite', 1], ['sql', 0.8]]],
  ['jedis', [['redis', 1], ['caching', 0.6]]],
  ['lettuce', [['redis', 1], ['caching', 0.6]]],
  ['spring-boot-starter-data-redis', [['redis', 1]]],
  ['mongodb-driver', [['mongodb', 1]]],
  ['spring-boot-starter-data-mongodb', [['mongodb', 1]]],
  ['kafka-clients', [['distributed-systems', 1]]],
  ['spring-kafka', [['distributed-systems', 1]]],
  ['amqp-client', [['distributed-systems', 1]]],
  ['grpc-', [['api-design', 0.9], ['distributed-systems', 0.6]]],
  ['jjwt', [['auth', 1], ['cryptography', 0.5]]],
  ['bouncycastle', [['cryptography', 1]]],
  ['bcprov', [['cryptography', 1]]],
  ['software.amazon.awssdk', [['aws', 1]]],
  ['aws-java-sdk', [['aws', 1]]],
  ['kotlinx-coroutines', [['concurrency', 1]]],
  ['ktor-server', [['http', 1]]],
  ['caffeine', [['caching', 1]]],
];

// ---- Container images (compose `image:` and Dockerfile FROM) -------------
// Matched against the image's repository basename (registry/org and tag stripped).
const IMAGES = {
  postgres: [['postgresql', 1], ['sql', 0.7]],
  postgis: [['postgresql', 1], ['sql', 0.7]],
  'timescaledb': [['postgresql', 1], ['sql', 0.7]],
  pgvector: [['postgresql', 1], ['sql', 0.7]],
  mysql: [['mysql', 1], ['sql', 0.7]],
  mariadb: [['mysql', 1], ['sql', 0.7]],
  redis: [['redis', 1], ['caching', 0.6]],
  valkey: [['redis', 1], ['caching', 0.6]],
  keydb: [['redis', 1], ['caching', 0.6]],
  memcached: [['caching', 1]],
  mongo: [['mongodb', 1]],
  mongodb: [['mongodb', 1]],
  nginx: [['http', 1], ['tls', 0.4]],
  caddy: [['http', 1], ['tls', 0.6]],
  traefik: [['http', 1], ['tls', 0.5]],
  haproxy: [['http', 0.9], ['tcp', 0.6]],
  httpd: [['http', 1]],
  rabbitmq: [['distributed-systems', 1]],
  kafka: [['distributed-systems', 1]],
  'cp-kafka': [['distributed-systems', 1]],
  redpanda: [['distributed-systems', 1]],
  zookeeper: [['distributed-systems', 0.9]],
  nats: [['distributed-systems', 1]],
  etcd: [['distributed-systems', 1], ['kubernetes', 0.4]],
  elasticsearch: [['distributed-systems', 0.7]],
  minio: [['aws', 0.5]],
  localstack: [['aws', 1]],
  node: [['nodejs', 1], ['javascript', 0.6]],
  python: [['python', 1]],
  golang: [['go', 1]],
  rust: [['rust', 1]],
  openjdk: [['java', 1]],
  'eclipse-temurin': [['java', 1]],
  maven: [['java', 0.9]],
  gradle: [['java', 0.9]],
  ubuntu: [['linux', 0.7]],
  debian: [['linux', 0.7]],
  alpine: [['linux', 0.7]],
  ollama: [['llm', 1]],
  'text-generation-inference': [['llm', 1]],
  vllm: [['llm', 1]],
  'vllm-openai': [['llm', 1]],
};

// ---- File extensions (census) --------------------------------------------
const EXT = {
  '.js': [['javascript', 1]],
  '.mjs': [['javascript', 1], ['nodejs', 0.5]],
  '.cjs': [['javascript', 1], ['nodejs', 0.6]],
  '.jsx': [['javascript', 1], ['react', 0.8]],
  '.ts': [['typescript', 1]],
  '.mts': [['typescript', 1]],
  '.cts': [['typescript', 1]],
  '.tsx': [['typescript', 1], ['react', 0.8]],
  '.py': [['python', 1]],
  '.pyi': [['python', 0.8]],
  '.ipynb': [['python', 0.8], ['ai-ml', 0.6]],
  '.go': [['go', 1]],
  '.rs': [['rust', 1]],
  '.java': [['java', 1]],
  '.kt': [['java', 0.8]],
  '.kts': [['java', 0.6]],
  '.scala': [['java', 0.5]],
  '.sh': [['bash', 1], ['linux', 0.5]],
  '.bash': [['bash', 1], ['linux', 0.5]],
  '.zsh': [['bash', 0.8]],
  '.css': [['css', 1]],
  '.scss': [['css', 1]],
  '.sass': [['css', 1]],
  '.less': [['css', 1]],
  '.html': [['browser', 0.8]],
  '.vue': [['browser', 0.8], ['javascript', 0.6]],
  '.svelte': [['browser', 0.8], ['javascript', 0.6]],
  '.sql': [['sql', 1]],
  '.prisma': [['prisma', 1], ['sql', 0.6]],
  '.graphql': [['api-design', 0.8]],
  '.gql': [['api-design', 0.8]],
  '.proto': [['api-design', 0.8], ['distributed-systems', 0.5]],
  '.tf': [['system-design', 0.3]],
  '.service': [['linux', 0.8]],
  '.pem': [['tls', 0.6]],
};

// Resolve a list of [topic, weight] pairs for a name from an exact map + prefix list.
function lookup(map, prefixes, name) {
  if (Object.prototype.hasOwnProperty.call(map, name)) return map[name];
  if (prefixes) {
    for (const [p, v] of prefixes) if (name.startsWith(p)) return v;
  }
  return null;
}

// Substring rules (Go module paths, JVM artifacts).
function lookupSubstring(rules, text) {
  const out = [];
  for (const [needle, v] of rules) if (text.includes(needle)) out.push([needle, v]);
  return out;
}

module.exports = {
  TOPICS, NPM, NPM_PREFIX, PY, GO, CARGO, CARGO_PREFIX, JVM, IMAGES, EXT,
  lookup, lookupSubstring,
};
